import { IEvent } from "@/models/veranstaltung"

export const EventService = {
    getEvents(): IEvent[] {
        return MOCK_DATA
    },
    formatDateToString(date: Date): string {
        const options: Intl.DateTimeFormatOptions = { day: '2-digit', month: '2-digit', year: 'numeric' }
        return date.toLocaleDateString('de-DE', options)
    },
}

const MOCK_DATA: IEvent[] = [
    {
        id: 1,
        title: "Technikmuseum Sonderausstellung",
        subtitle: "Digitale Revolution – Gestern und Heute",
        description: "Eine interaktive Ausstellung über die Geschichte der Computertechnik von den Anfängen bis zur KI.",
        category: "Ausstellung",
        date: new Date("2026-06-12"),
        fullday: true,
        image: "https://picsum.photos/seed/event1/800/400",
        web: "https://example.com/technikmuseum",
    },
    {
        id: 2,
        title: "Jazz im Hofgarten",
        subtitle: "Open-Air Konzert",
        description: "Lokale und internationale Jazzbands spielen bei freiem Eintritt im Hofgarten.",
        category: "Konzert",
        date: new Date("2026-06-14"),
        fullday: false,
        start: new Date("2026-06-14T18:00:00"),
        end: new Date("2026-06-14T22:30:00"),
        image: "https://picsum.photos/seed/event2/800/400",
        instagram: "https://instagram.com/jazzimhofgarten",
    },
    {
        id: 3,
        title: "Vue.js Meetup Hannover",
        subtitle: "Community Treffen für Frontend-Entwickler",
        description: "Talks zu Vue 3, Vite und modernen Migrationstrategien. Networking ab 19 Uhr.",
        category: "Meetup",
        date: new Date("2026-06-18"),
        fullday: false,
        start: new Date("2026-06-18T19:00:00"),
        end: new Date("2026-06-18T21:30:00"),
        web: "https://example.com/vuemeetup",
        facebook: "https://facebook.com/events/vuemeetup-hannover",
    },
    {
        id: 4,
        title: "Wochenmarkt Stadtmitte",
        category: "Markt",
        date: new Date("2026-06-20"),
        fullday: true,
    },
    {
        id: 5,
        title: "Filmvorführung: Past Lives",
        subtitle: "Sommerkino unter freiem Himmel",
        description: "Open-Air Screening mit anschließender Diskussion. Einlass ab 20:30 Uhr.",
        category: "Film",
        date: new Date("2026-06-21"),
        fullday: false,
        start: new Date("2026-06-21T21:00:00"),
        end: new Date("2026-06-21T23:15:00"),
        image: "https://picsum.photos/seed/event5/800/400",
        web: "https://example.com/sommerkino",
        instagram: "https://instagram.com/sommerkino_hh",
    },
    {
        id: 6,
        title: "Yoga & Meditation im Park",
        subtitle: "Kostenloser Morgen-Kurs",
        category: "Sport",
        date: new Date("2026-06-22"),
        fullday: false,
        start: new Date("2026-06-22T08:00:00"),
        end: new Date("2026-06-22T09:30:00"),
    },
    {
        id: 7,
        title: "Stadtführung: Historische Altstadt",
        subtitle: "Geführte Tour auf Deutsch und Englisch",
        description: "Entdecke verborgene Ecken und spannende Geschichten der Stadtgeschichte.",
        category: "Tour",
        date: new Date("2026-06-25"),
        fullday: false,
        start: new Date("2026-06-25T10:00:00"),
        end: new Date("2026-06-25T12:00:00"),
        web: "https://example.com/stadtfuehrung",
        facebook: "https://facebook.com/events/stadtfuehrung",
    },
    {
        id: 8,
        title: "Elektronik-Festival Maschsee",
        subtitle: "3 Stages, 40 Acts",
        description: "Das größte elektronische Musikfestival der Region mit nationalen und internationalen DJs.",
        category: "Festival",
        date: new Date("2026-06-27"),
        fullday: false,
        start: new Date("2026-06-27T14:00:00"),
        end: new Date("2026-06-28T04:00:00"),
        image: "https://picsum.photos/seed/event8/800/400",
        web: "https://example.com/elektronikfestival",
        instagram: "https://instagram.com/elektronikfestival",
        facebook: "https://facebook.com/events/elektronikfestival",
    },
    {
        id: 9,
        title: "Kindertheaterstück: Der kleine Prinz",
        category: "Theater",
        date: new Date("2026-06-28"),
        fullday: false,
        start: new Date("2026-06-28T15:00:00"),
        end: new Date("2026-06-28T16:30:00"),
        image: "https://picsum.photos/seed/event9/800/400",
        web: "https://example.com/kindertheater",
    },
    {
        id: 10,
        title: "Foodtruck-Festival Expo",
        subtitle: "Streetfood aus aller Welt",
        description: "Über 30 Foodtrucks, Live-Cooking-Shows und Musik. Eintritt frei.",
        category: "Food",
        date: new Date("2026-06-29"),
        fullday: true,
        image: "https://picsum.photos/seed/event10/800/400",
        facebook: "https://facebook.com/events/foodtruckfestival",
        instagram: "https://instagram.com/foodtruckfestival_expo",
    },
]
