export interface ILocation {
    id?: string,
    name: string,
    name2?: string,
    strasse: string,
    ort: string,
    plz: string,
    tel?: string,
    email?: string,
    home?: string,
    facebook?: string,
    instagram?: string,
    image?: string,
    info?: string,
}
